-- ============================================================================
-- Be Whole Care — production schema (PostgreSQL / Supabase)
--
-- AUTH MODEL — read this before changing anything.
--
-- This application does NOT use Supabase Auth. It has its own session layer
-- (scrypt password hashing, opaque server-side sessions, signed http-only
-- cookies) in lib/auth/. The Next.js server is therefore the ONLY client of
-- this database: the browser never holds a Supabase key and never issues a
-- query. Authorization is enforced in application code, where every
-- client-scoped read is filtered by the id derived from the session cookie.
--
-- Because of that, RLS here is not the authorization mechanism — it is a
-- blast shield. Every table has RLS enabled with NO permissive policies, so
-- the `anon` and `authenticated` roles can read nothing at all. If a Supabase
-- anon key were ever exposed, it would return zero rows from every table.
-- The server connects as the owner/service role, which bypasses RLS by design.
--
-- Integrity that must not depend on application code lives here instead:
--   * appointments_no_overlap  — double booking is impossible, full stop
--   * foreign keys + checks    — no orphaned or nonsensical rows
--   * unique indexes           — one calendar event per appointment, etc.
-- ============================================================================

create extension if not exists "pgcrypto";
create extension if not exists "citext";
create extension if not exists "btree_gist";

-- ---------------------------------------------------------------- enums ----
do $$ begin
  create type user_role as enum ('CLIENT', 'STAFF', 'ADMIN', 'SUPER_ADMIN');
  create type appointment_mode as enum ('online', 'in_person');
  create type appointment_status as enum ('pending_payment', 'confirmed', 'completed', 'cancelled', 'no_show');
  create type payment_method as enum ('card', 'medical_aid');
  create type payment_status as enum ('pending', 'processing', 'paid', 'failed', 'refunded', 'cancelled');
  create type follow_up_status as enum ('scheduled', 'awaiting_payment', 'paid', 'confirmed', 'completed', 'cancelled');
  create type notification_channel as enum ('email', 'whatsapp', 'sms', 'push', 'in_app');
  create type calendar_sync_status as enum ('synced', 'pending', 'failed', 'cancelled');
exception when duplicate_object then null;
end $$;

-- --------------------------------------------------------------- helpers ---
create or replace function set_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ------------------------------------------------------------------ users --
-- Ids are text rather than uuid: they are generated by the application
-- (newId('usr') -> "usr_xxx") so the same value is used in both data layers.
create table if not exists users (
  id             text primary key,
  email          citext not null unique,
  password_hash  text not null,
  role           user_role not null default 'CLIENT',
  email_verified boolean not null default false,
  disabled       boolean not null default false,
  is_demo        boolean not null default false,
  last_login_at  timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists users_role_idx on users(role);
drop trigger if exists users_updated on users;
create trigger users_updated before update on users
  for each row execute function set_updated_at();

create table if not exists sessions (
  token      text primary key,
  user_id    text not null references users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists sessions_user_idx on sessions(user_id);
-- Expired rows are pruned on write; this index keeps that cheap.
create index if not exists sessions_expiry_idx on sessions(expires_at);

create table if not exists profiles (
  id                text primary key,
  user_id           text not null unique references users(id) on delete cascade,
  first_name        text not null,
  last_name         text not null,
  phone             text,
  date_of_birth     date,
  -- Collected at booking. Address is optional (online clients need none);
  -- emergency contact is required by the booking form, but nullable here so
  -- that accounts created before this column existed remain valid.
  address           text,
  emergency_contact_name  text,
  emergency_contact_phone text,
  -- Only populated when the client chooses to claim from a medical aid.
  medical_aid       jsonb,
  preferred_contact text not null default 'email'
                    check (preferred_contact in ('email','whatsapp','sms')),
  notes             text,
  is_demo           boolean not null default false,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
drop trigger if exists profiles_updated on profiles;
create trigger profiles_updated before update on profiles
  for each row execute function set_updated_at();

-- ------------------------------------------------------------- catalogue ---
create table if not exists service_categories (
  id          text primary key,
  slug        text not null unique,
  name        text not null,
  summary     text not null,
  description text not null,
  areas       text[] not null default '{}',
  concerns    text[] not null default '{}',
  icon        text not null default 'Sprout',
  accent      text not null default 'forest',
  sort_order  int not null default 0,
  active      boolean not null default true
);

create table if not exists services (
  id                    text primary key,
  category_id           text not null references service_categories(id) on delete restrict,
  slug                  text not null unique,
  name                  text not null,
  summary               text not null,
  duration_minutes      int not null default 60 check (duration_minutes between 15 and 480),
  rate_band             text not null check (rate_band in ('individual','couple','assessment','free')),
  price_in_person_cents int not null default 0 check (price_in_person_cents >= 0),
  price_online_cents    int not null default 0 check (price_online_cents >= 0),
  allows_online         boolean not null default true,
  allows_in_person      boolean not null default true,
  requires_quote        boolean not null default false,
  intake_note           text,
  sort_order            int not null default 0,
  active                boolean not null default true,
  -- A service has to be bookable in at least one format.
  check (allows_online or allows_in_person)
);
create index if not exists services_category_idx on services(category_id) where active;

create table if not exists locations (
  id           text primary key,
  slug         text not null unique,
  name         text not null,
  address_line text not null,
  city         text not null,
  postal_code  text not null,
  region       text not null,
  active       boolean not null default true,
  sort_order   int not null default 0
);

create table if not exists practitioners (
  id            text primary key,
  user_id       text references users(id) on delete set null,
  display_name  text not null,
  title         text not null,
  bio           text,
  location_ids  text[] not null default '{}',
  offers_online boolean not null default true,
  active        boolean not null default true,
  is_demo       boolean not null default false
);

-- ---------------------------------------------------------- availability ---
create table if not exists availability_rules (
  id              text primary key,
  practitioner_id text references practitioners(id) on delete cascade,
  weekday         int not null check (weekday between 0 and 6),
  start_time      time not null,
  end_time        time not null,
  mode            text not null default 'any' check (mode in ('any','online','in_person')),
  location_id     text references locations(id) on delete set null,
  active          boolean not null default true,
  check (end_time > start_time)
);
create index if not exists availability_rules_weekday_idx on availability_rules(weekday) where active;

create table if not exists availability_blocks (
  id              text primary key,
  practitioner_id text references practitioners(id) on delete cascade,
  block_date      date not null,
  start_time      time,
  end_time        time,
  reason          text not null,
  created_at      timestamptz not null default now(),
  -- Either a whole-day block, or a properly ordered partial one.
  check ((start_time is null and end_time is null) or (start_time is not null and end_time > start_time))
);
create index if not exists availability_blocks_date_idx on availability_blocks(block_date);

-- ---------------------------------------------------------- appointments ---
create table if not exists appointments (
  id                  text primary key,
  reference           text not null unique,
  client_user_id      text not null references users(id) on delete cascade,
  service_id          text not null references services(id) on delete restrict,
  practitioner_id     text references practitioners(id) on delete set null,
  mode                appointment_mode not null,
  location_id         text references locations(id) on delete set null,
  start_at            timestamptz not null,
  end_at              timestamptz not null,
  duration_minutes    int not null,
  status              appointment_status not null default 'pending_payment',
  payment_method      payment_method not null,
  amount_cents        int not null default 0 check (amount_cents >= 0),
  reason              text,
  is_first_session    boolean not null default true,
  -- Outcome of the practice's medical aid verification. Null until decided.
  medical_aid_decision       text,
  medical_aid_decision_at    timestamptz,
  medical_aid_decline_reason text,
  session_link        text,
  calendar_event_id   text,
  cancelled_at        timestamptz,
  cancelled_by        text references users(id) on delete set null,
  cancellation_reason text,
  late_cancellation   boolean not null default false,
  rescheduled_from    text references appointments(id) on delete set null,
  completed_at        timestamptz,
  follow_up_id        text,
  is_demo             boolean not null default false,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  check (end_at > start_at),
  check (mode <> 'in_person' or location_id is not null)
);

-- THE important constraint. Two live appointments for the same practitioner
-- can never overlap in time — enforced by the database, so a race between two
-- simultaneous bookings ends with one of them getting a 23P01 error rather
-- than both succeeding. Application code must not be trusted with this.
alter table appointments drop constraint if exists appointments_no_overlap;
alter table appointments add constraint appointments_no_overlap
  exclude using gist (
    practitioner_id with =,
    tstzrange(start_at, end_at) with &&
  ) where (status in ('pending_payment','confirmed','completed'));

create index if not exists appointments_client_idx on appointments(client_user_id, start_at desc);
create index if not exists appointments_start_idx on appointments(start_at);
create index if not exists appointments_live_idx on appointments(start_at)
  where status in ('pending_payment','confirmed','completed');
drop trigger if exists appointments_updated on appointments;
create trigger appointments_updated before update on appointments
  for each row execute function set_updated_at();

-- --------------------------------------------------------------- payments --
create table if not exists payments (
  id                   text primary key,
  appointment_id       text references appointments(id) on delete set null,
  follow_up_id         text,
  client_user_id       text not null references users(id) on delete cascade,
  amount_cents         int not null check (amount_cents >= 0),
  currency             text not null default 'ZAR',
  method               payment_method not null,
  status               payment_status not null default 'pending',
  provider             text not null default 'peach',
  -- Provider-side references only. Card data never reaches this database.
  provider_checkout_id text,
  provider_payment_id  text,
  checkout_url         text,
  paid_at              timestamptz,
  failure_reason       text,
  is_demo              boolean not null default false,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
-- One row per provider checkout: makes webhook replay idempotent.
create unique index if not exists payments_checkout_idx on payments(provider_checkout_id)
  where provider_checkout_id is not null;
create index if not exists payments_client_idx on payments(client_user_id, created_at desc);
create index if not exists payments_appointment_idx on payments(appointment_id, created_at desc);
create index if not exists payments_status_idx on payments(status);
drop trigger if exists payments_updated on payments;
create trigger payments_updated before update on payments
  for each row execute function set_updated_at();

-- Append-only provider event log — the audit trail behind every status change.
create table if not exists payment_events (
  id         text primary key,
  payment_id text not null references payments(id) on delete cascade,
  type       text not null,
  payload    jsonb not null default '{}',
  created_at timestamptz not null default now()
);
create index if not exists payment_events_payment_idx on payment_events(payment_id, created_at);

-- ------------------------------------------------------------- follow-ups --
create table if not exists follow_ups (
  id                    text primary key,
  client_user_id        text not null references users(id) on delete cascade,
  service_id            text not null references services(id) on delete restrict,
  created_by_user_id    text references users(id) on delete set null,
  source_appointment_id text references appointments(id) on delete set null,
  appointment_id        text references appointments(id) on delete set null,
  due_date              date not null,
  preferred_time        time,
  mode                  appointment_mode not null default 'online',
  location_id           text references locations(id) on delete set null,
  payment_required      boolean not null default true,
  amount_cents          int not null default 0 check (amount_cents >= 0),
  status                follow_up_status not null default 'scheduled',
  reminder_date         date not null,
  reminder_sent_at      timestamptz,
  channel               text not null default 'email' check (channel in ('email','whatsapp','sms')),
  notes                 text,
  is_demo               boolean not null default false,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  -- The reminder cannot be scheduled after the thing it is reminding about.
  check (reminder_date <= due_date)
);
create index if not exists follow_ups_client_idx on follow_ups(client_user_id, due_date);
create index if not exists follow_ups_due_idx on follow_ups(due_date)
  where status in ('scheduled','awaiting_payment');
drop trigger if exists follow_ups_updated on follow_ups;
create trigger follow_ups_updated before update on follow_ups
  for each row execute function set_updated_at();

alter table payments drop constraint if exists payments_follow_up_fk;
alter table payments add constraint payments_follow_up_fk
  foreign key (follow_up_id) references follow_ups(id) on delete set null;
alter table appointments drop constraint if exists appointments_follow_up_fk;
alter table appointments add constraint appointments_follow_up_fk
  foreign key (follow_up_id) references follow_ups(id) on delete set null;

-- --------------------------------------------------------------- calendar --
create table if not exists calendar_events (
  id             text primary key,
  appointment_id text not null unique references appointments(id) on delete cascade,
  provider       text not null default 'google',
  external_id    text not null,
  calendar_id    text not null,
  html_link      text,
  status         calendar_sync_status not null default 'pending',
  last_error     text,
  synced_at      timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
-- One event per appointment per provider: a retried sync updates, never duplicates.
create unique index if not exists calendar_events_provider_external_idx
  on calendar_events(provider, external_id);
drop trigger if exists calendar_events_updated on calendar_events;
create trigger calendar_events_updated before update on calendar_events
  for each row execute function set_updated_at();

-- ---------------------------------------------------------- notifications --
create table if not exists notifications (
  id         text primary key,
  user_id    text references users(id) on delete cascade,
  audience   text not null check (audience in ('client','staff')),
  type       text not null,
  title      text not null,
  body       text not null,
  href       text,
  read       boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_idx on notifications(user_id, created_at desc);
create index if not exists notifications_audience_idx on notifications(audience, created_at desc);

create table if not exists notification_logs (
  id              text primary key,
  notification_id text references notifications(id) on delete set null,
  channel         notification_channel not null,
  recipient       text not null,
  subject         text not null,
  body            text not null default '',
  href            text,
  status          text not null default 'queued' check (status in ('queued','sent','failed')),
  provider        text not null,
  error           text,
  scheduled_for   timestamptz,
  sent_at         timestamptz,
  created_at      timestamptz not null default now()
);
-- The reminder worker polls exactly this predicate every few minutes.
create index if not exists notification_logs_due_idx on notification_logs(scheduled_for)
  where status = 'queued';
create index if not exists notification_logs_recipient_idx on notification_logs(recipient, created_at desc);

-- --------------------------------------------------------------- content ---
create table if not exists resources (
  id           text primary key,
  slug         text not null unique,
  title        text not null,
  excerpt      text not null,
  body         text not null,
  kind         text not null check (kind in ('article','reflection','podcast','worksheet')),
  topic        text not null,
  read_minutes int not null default 3,
  published    boolean not null default false,
  published_at timestamptz not null default now(),
  sort_order   int not null default 0
);

create table if not exists workshops (
  id             text primary key,
  slug           text not null unique,
  title          text not null,
  summary        text not null,
  description    text not null,
  audience       text not null,
  format         text not null check (format in ('online','in_person','hybrid')),
  workshop_date  date,
  duration_label text not null,
  status         text not null check (status in ('open','by_request','closed')),
  sort_order     int not null default 0
);

-- ------------------------------------------------------ notes and consent --
-- Administrative notes only. Clinical records are not kept in this system.
create table if not exists client_notes (
  id             text primary key,
  client_user_id text not null references users(id) on delete cascade,
  author_user_id text references users(id) on delete set null,
  appointment_id text references appointments(id) on delete set null,
  category       text not null check (category in ('admin','session_admin','billing')),
  body           text not null,
  is_demo        boolean not null default false,
  created_at     timestamptz not null default now()
);
create index if not exists client_notes_client_idx on client_notes(client_user_id, created_at desc);

create table if not exists consents (
  id         text primary key,
  user_id    text not null references users(id) on delete cascade,
  type       text not null check (type in ('terms','privacy','informed_consent','communications')),
  version    text not null,
  granted    boolean not null,
  granted_at timestamptz not null default now(),
  -- Hashed, never the raw address: POPIA data minimisation.
  ip_hash    text
);
create index if not exists consents_user_idx on consents(user_id, type);

create table if not exists audit_logs (
  id            text primary key,
  actor_user_id text references users(id) on delete set null,
  actor_role    user_role,
  action        text not null,
  entity        text not null,
  entity_id     text,
  meta          jsonb not null default '{}',
  created_at    timestamptz not null default now()
);
create index if not exists audit_logs_entity_idx on audit_logs(entity, entity_id, created_at desc);
create index if not exists audit_logs_created_idx on audit_logs(created_at desc);

create table if not exists settings (
  id         int primary key default 1 check (id = 1),
  data       jsonb not null,
  updated_at timestamptz not null default now()
);

-- ==================================================== row level security ====
-- Deny by default, everywhere. No policies are created, so `anon` and
-- `authenticated` can read and write nothing. The application connects as the
-- owner/service role and bypasses RLS; that connection is the only one that
-- ever exists, and it lives on the server.
do $$
declare t text;
begin
  foreach t in array array[
    'users','sessions','profiles','service_categories','services','locations',
    'practitioners','availability_rules','availability_blocks','appointments',
    'payments','payment_events','follow_ups','calendar_events','notifications',
    'notification_logs','resources','workshops','client_notes','consents',
    'audit_logs','settings'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('alter table %I force row level security', t);
  end loop;
end $$;

-- ============================================================= migrations ====
-- `create table if not exists` above does nothing to a database that already
-- has the table, so columns added after the first deploy must be applied
-- explicitly here. `add column if not exists` keeps the whole file idempotent:
-- it is still safe to run this script start to finish against any database,
-- new or existing.
--
-- Add new columns to BOTH the create-table block above (so a fresh database is
-- correct in one pass) and to this section (so existing databases catch up).

-- 2026-08: booking now collects an address and an emergency contact.
alter table profiles add column if not exists address text;
alter table profiles add column if not exists emergency_contact_name text;
alter table profiles add column if not exists emergency_contact_phone text;

-- 2026-08: Trauma, Grief & Healing withdrawn from the public site.
--
-- Deactivated rather than deleted. Appointments already booked against this
-- category and service still reference them; deleting the rows would leave
-- those records pointing at nothing. Setting `active = false` hides them from
-- the Services page and from booking while keeping history intact — and the
-- practice can reverse it from the admin dashboard at any time.
--
-- Seed changes do not touch an existing database, so this statement is what
-- actually applies the change in production.
update service_categories set active = false where slug = 'trauma-grief-and-healing';
update services set active = false where slug = 'trauma-grief-and-healing-session';

-- 2026-08: couples AND family sessions run 90 minutes; individual stays 60.
update services set duration_minutes = 90 where slug in ('couples-counselling', 'family-counselling');

-- ============================================================ maintenance ====
-- Reminder dispatch is driven by a scheduled call to /api/cron/reminders,
-- which reads notification_logs where status = 'queued' and scheduled_for <=
-- now(). See DEPLOY.md — on Vercel this is a cron entry in vercel.json.
--
-- Optional housekeeping if you prefer to run it in the database instead:
--   delete from sessions where expires_at < now();
